use_gpu: True

model_cfg: 'configs/model/farsecnn_NCars.yaml'

dataset_name: 'NCars'

batch_size: 16

log_mode: None #'neptune'
#neptune_api_key: {your api key}
#neptune_project: {your project name}
#neptune_run_id: {your training run id}

checkpoint_path: {path to model checkpoint}