seed: 123
use_gpu: True

model_cfg: 'configs/model/farsecnn_YOLO.yaml'

detection: True
dataset_name: 'Gen1_FULL'

batch_size: 8
gradient_batch_size: 256 # equivalent batch size for gradient accumulation
learning_rate: 1.0e-3


log_mode: 'neptune'
#neptune_api_key: {your api key}
#neptune_project: {your project name}
#neptune_log_model_checkpoints: False

save_checkpoint: True
max_epoch: 20
do_validation: False
early_stopping: False


### Resume run
#neptune_run_id: ''
#resume_ckpt: ''
